FROM quay.io/konveyor/builder AS builder
ENV GOPATH=$APP_ROOT
COPY . $APP_ROOT/src/velero-plugin-for-gcp
WORKDIR $APP_ROOT/src/velero-plugin-for-gcp
RUN CGO_ENABLED=0 GOOS=linux go build -v -o $APP_ROOT/bin/velero-plugin-for-gcp -mod=mod ./velero-plugin-for-gcp


FROM registry.access.redhat.com/ubi8-minimal
RUN mkdir /plugins
COPY --from=builder /opt/app-root/bin/velero-plugin-for-gcp /plugins/
USER 65534:65534
ENTRYPOINT ["/bin/bash", "-c", "cp /plugins/* /target/."]
